### ISSUE TITLE
support for linux/arm64/v8

### ISSUE THREAD

**Issue by mxsiet** [git-developer/tfrec-mqtt#1]
Is it possible to extend the IMAGE_PLATFORMS support https://github.com/git-developer/tfrec-mqtt/blob/main/.gitlab-ci.yml#L6 with `linux/arm64/v8`?

**Comment by git-developer** [comment]
I'd agree on adding this platform, but unfortunately [baycom/tfrec](https://github.com/baycom/tfrec) contains no matching `Makefile`, so the build fails. I see the following options: either request or contribute a `Makefile` to [baycom/tfrec](https://github.com/baycom/tfrec) or use the `arm/v7` image on your 64 bit arm devices.

**Comment by git-developer** [comment]
Since the best option would be to have a `Makefile` in the upstream repo, I opened a [pull request](https://github.com/baycom/tfrec/pull/24).

Until the PR is merged, you can try an image I created by [patching](https://github.com/git-developer/tfrec-mqtt/blob/04c6f64f89c6df0496cb5ec0052f0c07849e81be/image/Dockerfile.alpine#L22) the arm `Makefile` for arm64. I don't know if the compiler options are correct, but at least the build completes successfully.

I'm unable to test the image, so please give feedback whether the image works for you.

**Comment by git-developer** [comment]
The requested Docker image is available on Docker Hub and can be pulled from an arm64 machine as `ckware/tfrec-mqtt`.

Would you please test if it works for you and report back, @mxsiet?

**Comment by git-developer** [comment]
The feature is merged. This issue was closed due to inactivity. Please feel free to add comments if further discussion is desired.
